DROP TABLE accounts;

-- создаём таблицу
CREATE TABLE accounts
(
    id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client text,
    amount numeric
);


-- добавляем исходные данные
BEGIN;

    TRUNCATE TABLE accounts;

    INSERT INTO accounts
    VALUES (1, 'alice', 1000.00),
           (2, 'bob', 100.00),
           (3, 'bob', 900.00);

COMMIT;

select * from accounts;